[project]
name = "fast-api-prac1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "config>=0.5.1",
    "fastapi>=0.115.12",
    "uvicorn>=0.34.2",
]
