[project]
name = "fastapi-uv-practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.12",
    "psycopg[binary,pool]>=3.2.7",
    "uvicorn>=0.34.2",
]
